import sys

def i_just_throw_an_exception():
    print("Thanks for playing! Exiting gracefully.")
    sys.exit(0)